### PR TITLE
Add support for funced

### PR DESCRIPTION
**Pull request by wilriker**
Also fixed moving cursor to first empty line when using funced

### CODE REVIEW

**Comment by ElijahLynn** [comment]
Just checked this out (your master branch) and this is working great! Finally a pleasure to use funced with vim! Tabs and indents all work as expected and don't get reset every time I save.

This PR appears to have grown quite large and likely won't get merged as is. We should split this out to a specific branch with just the stuff needed to support `funced`.

**Comment by wilriker** [comment]
You are right, I forgot to put these changes on a branch (or better I never expected it to not get merged for so long and did not expect that any changes would be added to master in the mean time).

I now created a new branch "funced" only containing the relevant commits in my repo but there seams to be no way to change the source branch of a PR, is there?

**Comment by ElijahLynn** [comment]
Correct, there is no way to do so. You have to open a new one and close this one and link this one to the new one.

**Comment by wilriker** [comment]
Closed in favor of #41.

**Pull request closed without merging**
